# Welcome to Jekyll!

# Website settings
title: "Florian Robinet"
description: "Resume"
keywords: ""
url: "https://satacroteam.github.io"
baseurl: "/OnlineResume/"

# author
author:
  name: 'Florian Robinet'
  first_name: 'Florian'
  last_name: 'Robinet'
  email: 'florian.robinet.49000@hotmail.fr'
  facebook_username: ''
  github_username: ''
  avatar: 'static/img/landing/photo.png'
  desc: 'I am a data scientist with a strong background in mathematics, with data mining, machine learning and coding experience. \n
  Through academic and profesionnal projects, I gained significant data mining, machine learning and coding experience. \n
  Life is a continuous learning process, so work makes me more rigorous, musics makes my life more colorful.'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
